# Generated by Django 5.0.6 on 2024-06-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='desciption',
            new_name='descripcion',
        ),
    ]
